### ISSUE TITLE
Seek...

### ISSUE THREAD

**Issue by maru0123-2004** [Marusoftware/tkmedia3#7]

**Comment by maru0123-2004** [comment]
segmentation fault
```python
Fatal Python error: Segmentation fault

Current thread 0x00007fe72ca77700 (most recent call first):
  File "/home/maruo/\u30c9\u30ad\u30e5\u30e1\u30f3\u30c8/program/tkmedia3/media/_ffmpeg.py", line 112 in _loA non-intra slice in an IDR NAL unit.
ader
  File "/usr/lib/python3.8/threading.pydecode_slice_header error
", line 870 in run
  File "/usr/lib/python3.8/threadingno frame!
.py", line 932 in _bootstrap_inner
  File "/Exception in thread Thread-1:
usrTraceback (most recent call last):
/li  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
b/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fe72f27c700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 1202 in invoke_excepthook
  File "/usr/lib/python3.8/threading.py", line     self.run()
934 in   File "/usr/lib/python3.8/threading.py", line 870, in run
_bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fe7533c0740 (most recent call first):
  File "/usr/lib/python3.8/    self._target(*self._args, **self._kwargs)
tkin  File "/home/maruo/ドキュメント/program/tkmedia3/media/_ffmpeg.py", line 112, in _loader
ter/__init__.py", line 1429 in mainloop
  File "/hom    for frame in self.loader["generator"]:
e/mar  File "av/container/input.pyx", line 183, in decode
uo/\u30c9\u30ad\u30e5\u30e1\u30f3\u30c8/program/tkmedia3/test.py", line 25 in   File "av/packet.pyx", line 103, in av.packet.Packet.decode
<module>
Segmentation fault (コアダンプ)
```

**Comment by maru0123-2004** [comment]
Seg fault was fixed.
But it stop will stop....
